-- Creating a new database

CREATE DATABASE	SQLNOVEL;
USE SQLNOVEL;

-- showing the list of databases

SHOW DATABASES;

-- Creating table

CREATE TABLE AUTHOR
(
AUTHOR_NAME VARCHAR(50) NOT NULL ,
AUTHOR_PHONE int
);
INSERT INTO AUTHOR
(AUTHOR_NAME, AUTHOR_PHONE)
VALUES ('AJESH', 949629);
SELECT * FROM SQLNOVEL.AUTHOR;

CREATE TABLE TITLE
(
TitleName VARCHAR(100), 
Price INT,
PublicationDate DATE,
Royalty INT,
Title_ID INT PRIMARY KEY,
Advance INT
);
SELECT * FROM TITLE;
INSERT INTO TITLE
(TitleName,Price,PublicationDate, Royalty)
VALUES
('NEW', 9, '2025-08-01', 15),
('Book', 8, '2020-08-01',9);
SELECT * FROM TITLE ;

-- SELECTING ONLY THE REQUIRED COLUMNS

SELECT TitleName, Price FROM SQLNOVEL.TITLE;

-- RENAMING COLUMN NAME AS NEW NAME

SELECT PublicationDate AS PUBLISHED FROM TITLE;

-- Selecting data with Price less than 10.

SELECT * FROM TITLE WHERE Price < 10 AND Royalty = 15;
SELECT * FROM TITLE ;

-- CREATING CUSTOMER TABLE

CREATE TABLE CUSTOMER
(
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
PHONE_NO INT PRIMARY KEY,
STATE VARCHAR(50)
);
SELECT * FROM CUSTOMER;

-- INSERTING VALUES INTO CUSTOMER TABLE

INSERT INTO CUSTOMER
(FIRST_NAME,LAST_NAME,PHONE_NO)
VALUES
('RAJ','SHARMA', 00001),
('SAJI','DAS',001);
SELECT * FROM CUSTOMER;

-- SELECTING LAST NAME THAT STARTS WITH D

SELECT * FROM CUSTOMER WHERE LAST_NAME LIKE 'D%';
CREATE TABLE BOOK_TITLE
(
BookTitleName VARCHAR(100), 
Rate INT,
Pub_Date DATE,
Royalty_rate INT,
Title_ID INT PRIMARY KEY,
Advance INT
);
-- INSERTING VALUES INTO TABLE BOOK_TITLE

select * from BOOK_TITLE;
insert into BOOK_TITLE
(`BookTitleName`, `Rate`, `Pub_Date`, `Royalty_rate`, `Title_ID`, `Advance`)
values
('Book 1', 100, '2025-08-01', 10, 001, 5000),
('Book 2', 200, '2025-06-05',12, 002, 7500),
('Book 3', 300, '2025-05-01', 15, 003, 10000),
('Book 4', 400, '2025-04-02', 20, 004, 15000);

-- SELECTING COLUMNS WITH CONDITIONS

select * from BOOK_TITLE;
SELECT BookTitleName, Title_ID, Advance FROM BOOK_TITLE 
WHERE Advance BETWEEN 5000 AND 10000 AND Royalty_rate = 10;

-- ORDER BY CUSTOMER LAST NAME IN DESCENDING ORDER

SELECT * FROM CUSTOMER ORDER BY LAST_NAME DESC;

-- ORDER BY CUSTOMER FIRST NAME IN ASCENDING ORDER

SELECT * FROM CUSTOMER ORDER BY FIRST_NAME ASC;
ALTER TABLE CUSTOMER
ADD STATE VARCHAR(50);
ALTER TABLE CUSTOMER
ADD CITY VARCHAR(50);
SELECT * FROM CUSTOMER;
-- SELECTING UNIQUE CITIES FROM CUSTOMER TABLE
SELECT DISTINCT CITY
FROM CUSTOMER;

-- CREATING TABLE ORDERITEM

CREATE TABLE ORDERITEM
(
ORDERID INT NOT NULL PRIMARY KEY,
TITLEID INT NOT NULL ,
ITEM_PRICE INT 
);

-- INSERTING VALUES INTO TABLE ORDERITEM

SELECT * FROM ORDERITEM;
INSERT INTO ORDERITEM
(`ORDERID`, `TITLEID`, `ITEM_PRICE`)
VALUES
(8,881,1322),
(13,13113,211);

-- SELECTING VALUES OF TABLE ACCORDING TO INCREASING PRICE

SELECT ORDERID,TITLEID,ITEM_PRICE FROM ORDERITEM
ORDER BY ITEM_PRICE ASC LIMIT 5;

